# Generated by Django 6.0.6 on 2026-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_barres', models.CharField(blank=True, max_length=255, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField(default=0)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
